name: Generate LAA IP Allowlist

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  get-allowlist:
    uses: ministryofjustice/laa-ip-allowlist/.github/workflows/generate-allowlist.yml@v1.1.0
    with:
      # Separate tags within a group with spaces, separate groups with semicolons
      groups: "external mp-nonlive;external mp-live"

  deploy:
    needs: get-allowlist
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with allowlist
        run: |
          echo "${{ needs.get-allowlist.outputs.allowlist }}"
        # You can use the below 
        # helm upgrade my-app ./chart \
        #            --set ingress.allowList="${{ needs.get-allowlist.outputs.allowlist }}"          